services:
  iosbot.bot:
    image: iosbot.bot
    build:
      context: .
      dockerfile: iOSBot.Bot/Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    secrets:
      - botToken
      - dbPass
secrets:
  botToken:
    file: ./secrets/botToken.txt
  dbPass:
    file: ./secrets/dbPass.txt